-- Tablas de Parámetros de Ahorros

-- CCACODPRO: Maestros de Productos
CREATE TABLE IF NOT EXISTS CCACODPRO (
    CODPRO NUMERIC(3,0) PRIMARY KEY,
    DESCRI VARCHAR(30),
    TIPMON NUMERIC(1,0),
    CODUNI NUMERIC(5,0),
    TIPLIQ NUMERIC(1,0),
    PERCAU NUMERIC(1,0),
    VMLINT NUMERIC(15,2),
    VMAPER NUMERIC(15,2),
    VMCUEN NUMERIC(15,2),
    PLNINT NUMERIC(5,0),
    ENVCOR NUMERIC(3,0),
    FECLIQ NUMERIC(8,0),
    INDCIE NUMERIC(1,0),
    TASRET NUMERIC(11,7),
    VLRRET NUMERIC(15,2),
    SALNEM NUMERIC(15,2),
    USRACT VARCHAR(10),
    FCHACT NUMERIC(8,0),
    HORACT NUMERIC(8,0)
);

-- CCACODTAS: Histórico de Tasas
CREATE TABLE IF NOT EXISTS CCACODTAS (
    CODSIS NUMERIC(5,0),
    CODTAS NUMERIC(5,0),
    FEEFEC NUMERIC(8,0),
    CODUNI NUMERIC(5,0),
    PUNADI NUMERIC(17,8),
    VLRTAS NUMERIC(17,8),
    PERTAS NUMERIC(2,0),
    FORAPL NUMERIC(2,0),
    INDRED NUMERIC(1,0),
    INDCAL NUMERIC(1,0),
    INDMOD NUMERIC(1,0),
    VLRMIN NUMERIC(17,8),
    VLRMAX NUMERIC(17,8),
    TASRED NUMERIC(5,0),
    EFEDIA NUMERIC(17,8),
    USRACT VARCHAR(10),
    FCHACT NUMERIC(8,0),
    HORACT NUMERIC(8,0),
    PRIMARY KEY (CODSIS, CODTAS, FEEFEC)
);

-- CCANOMTAS: Nombres de Tasas
CREATE TABLE IF NOT EXISTS CCANOMTAS (
    CODSIS NUMERIC(5,0),
    CODTAS NUMERIC(5,0),
    NOMTAS VARCHAR(30),
    SIGTAS VARCHAR(5),
    TIPTAS NUMERIC(1,0),
    CLATAS NUMERIC(1,0),
    USRACT VARCHAR(10),
    FCHACT NUMERIC(8,0),
    HORACT NUMERIC(8,0),
    PRIMARY KEY (CODSIS, CODTAS)
);

-- CCAPARGEN: Parámetros Generales de Ahorros
CREATE TABLE IF NOT EXISTS CCAPARGEN (
    CODCIA NUMERIC(3,0) PRIMARY KEY,
    FECLIQ NUMERIC(8,0),
    INDCIE NUMERIC(1,0),
    TASRET NUMERIC(11,7),
    VLRRET NUMERIC(15,2),
    SALNEM NUMERIC(15,2),
    VLREFE NUMERIC(15,2),
    VLRCNJ NUMERIC(15,2),
    TRAABO NUMERIC(5,0),
    TRARET NUMERIC(5,0),
    TRACAU NUMERIC(5,0),
    TRAINT NUMERIC(5,0),
    TRARES NUMERIC(5,0),
    TRAREV NUMERIC(5,0),
    TRAAJU NUMERIC(5,0),
    TRAACT NUMERIC(5,0),
    TRAINA NUMERIC(5,0),
    TRA001 NUMERIC(5,0),
    TRA002 NUMERIC(5,0),
    TRA003 NUMERIC(5,0),
    TRA004 NUMERIC(5,0),
    TRA005 NUMERIC(5,0),
    TRARNC NUMERIC(5,0),
    TRARNP NUMERIC(5,0),
    TRARNI NUMERIC(5,0),
    TRARAC NUMERIC(5,0),
    TRARAP NUMERIC(5,0),
    TRARAI NUMERIC(5,0),
    TRARCC NUMERIC(5,0),
    TRARCP NUMERIC(5,0),
    TRARCI NUMERIC(5,0),
    TRARPG NUMERIC(5,0),
    TRARCB NUMERIC(5,0),
    VLR001 NUMERIC(15,2),
    VLR002 NUMERIC(15,2),
    VLR003 NUMERIC(15,2),
    VLR004 NUMERIC(15,2),
    VLR005 NUMERIC(15,2),
    IND001 NUMERIC(1,0),
    IND002 NUMERIC(1,0),
    IND003 NUMERIC(1,0),
    IND004 NUMERIC(1,0),
    IND005 NUMERIC(1,0),
    USRACT VARCHAR(10),
    FCHACT NUMERIC(8,0),
    HORACT NUMERIC(8,0)
);

-- CCATABINT: Interfases de Entrada
CREATE TABLE IF NOT EXISTS CCATABINT (
    NOMARC VARCHAR(10) PRIMARY KEY,
    DESCRI VARCHAR(50),
    INDDLT NUMERIC(1,0),
    INDNOV NUMERIC(1,0),
    ACUCREBOK NUMERIC(15,2),
    ACUDEBBOK NUMERIC(15,2),
    NROREGBOK NUMERIC(7,0),
    ACUCRELOK NUMERIC(15,2),
    ACUDEBLOK NUMERIC(15,2),
    NROREGLOK NUMERIC(7,0),
    ACUCREBER NUMERIC(15,2),
    ACUDEBBER NUMERIC(15,2),
    NROREGBER NUMERIC(7,0),
    ACUCRELER NUMERIC(15,2),
    ACUDEBLER NUMERIC(15,2),
    NROREGLER NUMERIC(7,0),
    NOMLIB VARCHAR(10),
    NOMDIS VARCHAR(10),
    INDHAB NUMERIC(1,0),
    USRACT VARCHAR(10),
    FCHACT NUMERIC(8,0),
    HORACT NUMERIC(8,0)
);

-- CCATRAPRO: Transformación Proceso/Producto
CREATE TABLE IF NOT EXISTS CCATRAPRO (
    CODPRO NUMERIC(5,0),
    PRODUC NUMERIC(5,0),
    TRADEB NUMERIC(5,0),
    TRACRE NUMERIC(5,0),
    TIPVAL NUMERIC(1,0),
    CODTAR NUMERIC(5,0),
    USRACT VARCHAR(10),
    FCHACT NUMERIC(8,0),
    HORACT NUMERIC(8,0),
    PRIMARY KEY (CODPRO, PRODUC, TRADEB, TRACRE)
);
